// SPDX-License-Identifier: Apache-2.0
package protocol_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/webcodex/protocol"
)

// This independent table is source-derived, not generated by a Go or Rust executor.
type skillReadFixture struct {
	SchemaVersion  int                                   `json:"schema_version"`
	SourceCommit   string                                `json:"source_commit"`
	Provenance     string                                `json:"provenance"`
	BaseRequest    map[string]json.RawMessage            `json:"base_request"`
	BaseInvocation map[string]map[string]json.RawMessage `json:"base_invocation"`
	Cases          []struct {
		Name              string                     `json:"name"`
		Set               map[string]json.RawMessage `json:"set"`
		Omit              []string                   `json:"omit"`
		RawWire           string                     `json:"raw_wire"`
		Outcome           string                     `json:"outcome"`
		ExpectedWireKind  string                     `json:"expected_wire_kind"`
		ExpectedMetadata  map[string]json.RawMessage `json:"expected_metadata"`
		ExpectedOperation map[string]json.RawMessage `json:"expected_operation"`
	} `json:"cases"`
	DeferredFileKinds []string `json:"deferred_file_kinds"`
}

func skillFixture(t *testing.T) skillReadFixture {
	t.Helper()
	b, err := os.ReadFile("testdata/skill-file-read.json")
	if err != nil {
		t.Fatal(err)
	}
	var f skillReadFixture
	if err := json.Unmarshal(b, &f); err != nil {
		t.Fatal(err)
	}
	if f.SchemaVersion != 1 || f.SourceCommit != "97ad66949a859174911c2f6da2ff1063be98bfa9" || f.Provenance == "" {
		t.Fatal("fixture provenance changed")
	}
	if len(f.Cases) != 35 || len(f.DeferredFileKinds) != 16 {
		t.Fatal("fixture coverage count changed")
	}
	return f
}

func mergeSkillFields(base, overlay map[string]json.RawMessage, omit []string) map[string]json.RawMessage {
	out := make(map[string]json.RawMessage, len(base))
	for k, v := range base {
		out[k] = v
	}
	for _, k := range omit {
		delete(out, k)
	}
	for k, v := range overlay {
		out[k] = v
	}
	return out
}

func losslessSkillJSON(t *testing.T, value any) any {
	t.Helper()
	b, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	var out any
	if err := d.Decode(&out); err != nil {
		t.Fatal(err)
	}
	return out
}

// Project only original canonical fields: this is a test adapter, not a new wire codec.
func skillCanonical(i protocol.Invocation) map[string]any {
	f := i.Operation.(protocol.FileOperation)
	p := f.Payload
	return map[string]any{
		"metadata":  map[string]any{"request_id": i.Metadata.RequestID, "client_id": i.Metadata.ClientID, "requested_by": i.Metadata.RequestedBy, "created_at": i.Metadata.CreatedAt},
		"operation": map[string]any{"kind": f.WireKind(), "cwd": p.Cwd, "path": p.Path, "content": p.Content, "max_bytes": p.MaxBytes, "expected_sha256": p.ExpectedSHA256, "expected_prefix": p.ExpectedPrefix, "start_line": p.StartLine, "end_line": p.EndLine, "create_dirs": p.CreateDirs},
	}
}

func TestSkillFileReadSourceFixtures(t *testing.T) {
	f := skillFixture(t)
	seen := map[string]bool{}
	for _, c := range f.Cases {
		t.Run(c.Name, func(t *testing.T) {
			if seen[c.Name] {
				t.Fatal("duplicate case name")
			}
			seen[c.Name] = true
			wire, err := json.Marshal(mergeSkillFields(f.BaseRequest, c.Set, c.Omit))
			if err != nil {
				t.Fatal(err)
			}
			if c.RawWire != "" {
				wire = []byte(c.RawWire)
			}
			r, err := protocol.ReadRequest(wire)
			if c.Outcome == "wire_reject" {
				if err == nil {
					t.Fatal("wire rejection expected")
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if c.ExpectedWireKind != "" && r.Kind != c.ExpectedWireKind {
				t.Fatalf("wire kind %q", r.Kind)
			}
			i, err := r.DecodeInvocation()
			if c.Outcome == "invalid" {
				if err == nil || errors.Is(err, protocol.ErrUnsupported) || errors.Is(err, protocol.ErrUnknownKind) {
					t.Fatalf("canonical invalid expected: %v", err)
				}
				return
			}
			if c.Outcome != "accept" {
				t.Fatalf("unknown outcome %q", c.Outcome)
			}
			if err != nil {
				t.Fatal(err)
			}
			if _, ok := i.Operation.(protocol.FileOperation); !ok {
				t.Fatalf("non-file operation %T", i.Operation)
			}
			expected := map[string]any{
				"metadata":  mergeSkillFields(f.BaseInvocation["metadata"], c.ExpectedMetadata, nil),
				"operation": mergeSkillFields(f.BaseInvocation["operation"], c.ExpectedOperation, nil),
			}
			if got, want := losslessSkillJSON(t, skillCanonical(i)), losslessSkillJSON(t, expected); !reflect.DeepEqual(got, want) {
				t.Fatalf("canonical fields:\ngot %#v\nwant %#v", got, want)
			}
			// Required timeout stays on RunnerRequest; canonical File payload has no timeout.
			round, err := json.Marshal(r)
			if err != nil {
				t.Fatal(err)
			}
			restored, err := protocol.ReadRequest(round)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(restored, r) {
				t.Fatal("request roundtrip changed optional/wide fields")
			}
			public, err := protocol.DecodeRequest(wire)
			if err != nil || !reflect.DeepEqual(public, i) {
				t.Fatalf("public decoder differs: %v", err)
			}
			if _, err := r.DecodeJobInvocation(); !errors.Is(err, protocol.ErrUnsupported) {
				t.Fatalf("sync kind in Job decoder: %v", err)
			}
			if _, err := protocol.DecodeJobRequest(wire); !errors.Is(err, protocol.ErrUnsupported) {
				t.Fatalf("sync wire in Job decoder: %v", err)
			}
		})
	}
}

func TestSkillFileReadHistoricalDeferredFileKinds(t *testing.T) {
	f := skillFixture(t)
	for _, kind := range f.DeferredFileKinds {
		t.Run(kind, func(t *testing.T) {
			k, _ := json.Marshal(kind)
			b, _ := json.Marshal(mergeSkillFields(f.BaseRequest, map[string]json.RawMessage{"kind": k}, []string{"start_line", "end_line"}))
			r, err := protocol.ReadRequest(b)
			if err != nil {
				t.Fatal(err)
			}
			inv, err := r.DecodeInvocation()
			// Keep the prior fixture immutable; these kinds were added afterward.
			if kind == "file_skill_list_packages" || kind == "file_project_overview" || kind == "file_write_project_file" {
				if err != nil || inv.Operation.WireKind() != kind {
					t.Fatalf("newly supported File kind: %v", err)
				}
			} else if !errors.Is(err, protocol.ErrUnsupported) {
				t.Fatalf("sync: %v", err)
			}
			if _, err := r.DecodeJobInvocation(); !errors.Is(err, protocol.ErrUnsupported) {
				t.Fatalf("Job: %v", err)
			}
		})
	}
}

func TestSkillFileReadCanonicalOwnershipAndFieldSet(t *testing.T) {
	f := skillFixture(t)
	b, _ := json.Marshal(f.BaseRequest)
	r, err := protocol.ReadRequest(b)
	if err != nil {
		t.Fatal(err)
	}
	i, err := r.DecodeInvocation()
	if err != nil {
		t.Fatal(err)
	}
	before := losslessSkillJSON(t, skillCanonical(i))
	*r.Path = "changed"
	*r.Content = "changed"
	*r.Cwd = "/other"
	*r.StartLine = 9
	*r.EndLine = 99
	if !reflect.DeepEqual(before, losslessSkillJSON(t, skillCanonical(i))) {
		t.Fatal("request mutation retargeted invocation")
	}
	if reflect.TypeFor[protocol.RunnerRequest]().NumField() != 27 || reflect.TypeFor[protocol.FilePayload]().NumField() != 9 {
		t.Fatal("original field set expanded")
	}
	// Exact projection equality above refuses accidental canonical timeout, package_root,
	// max_file_bytes, nested payload, or content-object expectations in the shared table.
}
