package service

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/coder/websocket"
	"github.com/stretchr/testify/require"
)

// Synthetic documents generated by the official yjs 13.6.27 implementation.
// No HAR bytes, identifiers, credentials or user content are committed.
func prismYFixtures(t *testing.T) map[string][]byte {
	t.Helper()
	raw, err := os.ReadFile("testdata/prism_yjs_fixtures.json")
	require.NoError(t, err)
	var encoded map[string]string
	require.NoError(t, json.Unmarshal(raw, &encoded))
	result := make(map[string][]byte)
	for name, value := range encoded {
		result[name], err = base64.StdEncoding.DecodeString(value)
		require.NoError(t, err)
	}
	return result
}

func TestOpenAIPrismYjsOfficialInteropFixtures(t *testing.T) {
	fixtures := prismYFixtures(t)
	require.Equal(t, fixtures["insert"], prismEncodeYFile(200, "file-test", "diagram.png", "root-test"))
	require.Equal(t, fixtures["new"], prismEncodeYNewProjectFile(300, "file-test", "diagram.png", "root-test"))
	for _, name := range []string{"initial", "complex"} {
		doc, err := prismReadYUpdate(fixtures[name])
		require.NoError(t, err)
		root, exists, err := doc.rootFolder("file-test", "diagram.png")
		require.NoError(t, err)
		require.Equal(t, "root-test", root)
		require.False(t, exists)
	}
	for _, name := range []string{"verified", "new"} {
		doc, err := prismReadYUpdate(fixtures[name])
		require.NoError(t, err)
		_, exists, err := doc.rootFolder("file-test", "diagram.png")
		require.NoError(t, err)
		require.True(t, exists)
		_, _, err = doc.rootFolder("another-id", "diagram.png")
		require.ErrorContains(t, err, "already contains")
	}
	for _, data := range [][]byte{{255}, {1, 1}, {0, 0, 99}, bytes.Repeat([]byte{255}, 20)} {
		_, err := prismReadYUpdate(data)
		require.Error(t, err)
	}
}

func TestOpenAIPrismAttachProjectFileWaitsForRemoteAcknowledgement(t *testing.T) {
	fixtures := prismYFixtures(t)
	for _, tc := range []struct {
		name    string
		initial []byte
		ack     bool
	}{{"existing root", fixtures["initial"], true}, {"empty project", []byte{0, 0}, true}, {"missing acknowledgement", fixtures["initial"], false}} {
		t.Run(tc.name, func(t *testing.T) {
			waited := false
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				switch r.URL.Path {
				case "/api/y":
					w.Header().Set("Content-Type", "application/json")
					_, _ = w.Write(prismMustJSON(map[string]string{"docId": "project-test", "url": "ws://" + r.Host + "/y/d/project-test/ws", "token": "document-secret"}))
				case "/s/sandboxes/proxy/wait-for-sync":
					waited = true
					require.Equal(t, "sandbox-secret", r.Header.Get("x-crixet-sandbox-token"))
					_, _ = w.Write([]byte(`{"status":"synced"}`))
				case "/y/d/project-test/ws":
					require.Equal(t, "document-secret", r.URL.Query().Get("token"))
					require.Contains(t, r.Header.Get("Cookie"), "prism_oai_access_token=access-secret")
					conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{InsecureSkipVerify: true})
					require.NoError(t, err)
					defer func() { _ = conn.CloseNow() }()
					_, frame, err := conn.Read(r.Context())
					require.NoError(t, err)
					require.Equal(t, prismYSyncFrame(0, []byte{0}), frame)
					require.NoError(t, conn.Write(r.Context(), websocket.MessageBinary, prismYSyncFrame(0, []byte{0})))
					require.NoError(t, conn.Write(r.Context(), websocket.MessageBinary, prismYSyncFrame(1, tc.initial)))
					_, frame, err = conn.Read(r.Context())
					require.NoError(t, err)
					require.Equal(t, prismYSyncFrame(1, []byte{0, 0}), frame)
					_, frame, err = conn.Read(r.Context())
					require.NoError(t, err)
					reader := &prismYReader{data: frame}
					require.Equal(t, uint64(0), reader.uint())
					require.Equal(t, uint64(2), reader.uint())
					update := reader.bytes()
					require.NoError(t, reader.err)
					_, frame, err = conn.Read(r.Context())
					require.NoError(t, err)
					require.Equal(t, prismYSyncFrame(0, []byte{0}), frame)
					verified := tc.initial
					if tc.ack {
						if len(tc.initial) == 2 {
							verified = update
						} else {
							verified = append([]byte{2}, update[1:len(update)-1]...)
							verified = append(verified, tc.initial[1:]...)
						}
					}
					require.NoError(t, conn.Write(r.Context(), websocket.MessageBinary, prismYSyncFrame(1, verified)))
				default:
					t.Errorf("unexpected endpoint %s", r.URL.Path)
					w.WriteHeader(http.StatusNotFound)
				}
			}))
			defer server.Close()
			upstream := prismUpstreamFunc(func(req *http.Request) (*http.Response, error) { return server.Client().Do(req) })
			transport := NewOpenAIPrismTransportFromUpstream(upstream, OpenAIPrismTransportOptions{BaseURL: server.URL})
			path, err := transport.AttachProjectFile(context.Background(), &Account{ID: 1}, "access-secret", "project-test", "file-test", "diagram.png", "sandbox-secret")
			if tc.ack {
				require.NoError(t, err)
				require.Equal(t, "diagram.png", path)
				require.True(t, waited)
			} else {
				require.ErrorContains(t, err, "acknowledge")
				require.False(t, waited)
			}
		})
	}
}

func TestOpenAIPrismAttachRejectsRedirectBeforeCredentialsLeaveOrigin(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/api/y" {
			_, _ = w.Write(prismMustJSON(map[string]string{"docId": "project-test", "url": "ws://" + r.Host + "/y/d/project-test/ws", "token": "document-secret"}))
			return
		}
		http.Redirect(w, r, "https://other.example/ws", http.StatusTemporaryRedirect)
	}))
	defer server.Close()
	transport := NewOpenAIPrismTransportFromUpstream(prismUpstreamFunc(func(req *http.Request) (*http.Response, error) { return server.Client().Do(req) }), OpenAIPrismTransportOptions{BaseURL: server.URL})
	_, err := transport.AttachProjectFile(context.Background(), &Account{ID: 1}, "access-secret", "project-test", "file-test", "diagram.png", "sandbox-secret")
	require.Error(t, err)
	require.NotContains(t, err.Error(), "document-secret")
}

func TestOpenAIPrismReadLimitsRejectTruncatedSuccess(t *testing.T) {
	upstream := prismUpstreamFunc(func(req *http.Request) (*http.Response, error) {
		return &http.Response{StatusCode: http.StatusOK, Header: http.Header{}, Body: io.NopCloser(io.MultiReader(io.LimitReader(&prismRepeatedByteReader{}, 32<<20), strings.NewReader("x")))}, nil
	})
	transport := NewOpenAIPrismTransportFromUpstream(upstream, OpenAIPrismTransportOptions{})
	_, _, err := transport.doJSON(context.Background(), &Account{ID: 1}, "access-secret", http.MethodGet, "/test", nil)
	require.ErrorContains(t, err, "size limit")
}

type prismRepeatedByteReader struct{}

func (*prismRepeatedByteReader) Read(p []byte) (int, error) {
	for i := range p {
		p[i] = 'x'
	}
	return len(p), nil
}
